<?php
if (!defined('ABSPATH')) exit;

/** @var WC_Order $order */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice #<?php echo $order->get_id(); ?></title>
    <style>
        body { font-family: Arial, sans-serif; color: #333; margin: 20px; }
        header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        header img { max-height: 60px; }
        h1 { color: #0073aa; margin: 0; }
        .section { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
        th { background: #f1f1f1; }
        tbody tr:nth-child(even) { background: #f9f9f9; }
        .total-row td { font-weight: bold; text-align: right; }
        .notes { margin-top: 20px; }
        .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #777; }
        .print-button { margin-bottom: 20px; }
        @media print { .print-button { display: none; } }
    </style>
</head>
<body>

<button class="print-button" onclick="window.print();">Print Invoice</button>

<header>
    <div class="company-info">
        <?php if(get_option('aipd_company_logo')): ?>
            <img src="<?php echo esc_url(get_option('aipd_company_logo')); ?>" alt="Logo">
        <?php endif; ?>
        <p><strong><?php echo esc_html(get_option('aipd_company_name', 'Company Name')); ?></strong></p>
        <p><?php echo esc_html(get_option('aipd_company_address', 'Address')); ?></p>
        <p>Phone: <?php echo esc_html(get_option('aipd_company_phone', '0123456789')); ?></p>
        <p>Email: <?php echo esc_html(get_option('aipd_company_email', 'email@example.com')); ?></p>
    </div>
    <h1>Invoice #<?php echo $order->get_id(); ?></h1>
</header>

<div class="section">
    <p><strong>Customer:</strong> <?php echo esc_html($order->get_formatted_billing_full_name()); ?></p>
    <p><strong>Billing Address:</strong> <?php echo esc_html($order->get_formatted_billing_address()); ?></p>
    <p><strong>Shipping Address:</strong> <?php echo esc_html($order->get_formatted_shipping_address()); ?></p>
    <p><strong>Email:</strong> <?php echo esc_html($order->get_billing_email()); ?></p>
    <p><strong>Phone:</strong> <?php echo esc_html($order->get_billing_phone()); ?></p>
</div>

<div class="section">
    <p><strong>Invoice Date:</strong> <?php echo esc_html(wc_format_datetime($order->get_date_created())); ?></p>
    <p><strong>Payment Method:</strong> <?php echo esc_html($order->get_payment_method_title()); ?></p>
</div>

<table>
    <thead>
        <tr>
            <th>Product</th>
            <th>SKU</th>
            <th>Qty</th>
            <th>Unit Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($order->get_items() as $item):
            $product = $item->get_product();
            $sku = $product ? $product->get_sku() : '';
        ?>
        <tr>
            <td><?php echo esc_html($item->get_name()); ?></td>
            <td><?php echo esc_html($sku); ?></td>
            <td><?php echo esc_html($item->get_quantity()); ?></td>
            <td><?php echo wc_price($order->get_item_total($item, true)); ?></td>
            <td><?php echo wc_price($item->get_total()); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr class="total-row">
            <td colspan="4">Subtotal:</td>
            <td><?php echo wc_price($order->get_subtotal()); ?></td>
        </tr>
        <?php if($order->get_total_tax() > 0): ?>
        <tr class="total-row">
            <td colspan="4">Tax:</td>
            <td><?php echo wc_price($order->get_total_tax()); ?></td>
        </tr>
        <?php endif; ?>
        <?php if($order->get_discount_total() > 0): ?>
        <tr class="total-row">
            <td colspan="4">Discount:</td>
            <td><?php echo wc_price($order->get_discount_total()); ?></td>
        </tr>
        <?php endif; ?>
        <tr class="total-row">
            <td colspan="4">Total:</td>
            <td><?php echo $order->get_formatted_order_total(); ?></td>
        </tr>
    </tfoot>
</table>

<?php if($order->get_customer_note()): ?>
<div class="notes">
    <strong>Customer Notes:</strong>
    <p><?php echo esc_html($order->get_customer_note()); ?></p>
</div>
<?php endif; ?>

<div class="footer">
    <?php echo esc_html(get_option('aipd_footer_text','Thank you for your order!')); ?><br>
    Generated by <?php bloginfo('name'); ?>.
</div>

</body>
</html>
