<?php
if (!defined('ABSPATH')) exit;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Package #<?php echo $order->get_id(); ?></title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; margin: 20px; }
        header { display: flex; justify-content: space-between; align-items: center; background: #0073aa; color: #fff; padding: 15px; }
        header img { max-height: 60px; }
        h1 { margin: 0; font-size: 24px; }
        .company-info, .customer-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background: #f7f7f7; }
        tbody tr:nth-child(even) { background: #f9f9f9; }
        .notes { margin-top: 20px; }
        .footer { text-align: center; margin-top: 50px; font-size: 12px; color: #777; }
        .print-button { margin-bottom: 20px; }
        @media print { .print-button { display: none; } }
    </style>
</head>
<body>

<button class="print-button" onclick="window.print();">Print Package Slip</button>

<header>
    <div class="company-info">
        <?php if(get_option('aipd_company_logo')): ?>
            <img src="<?php echo esc_url(get_option('aipd_company_logo')); ?>" alt="Logo">
        <?php endif; ?>
        <p><strong><?php echo esc_html(get_option('aipd_company_name', 'Company Name')); ?></strong></p>
        <p><?php echo esc_html(get_option('aipd_company_address', 'Address')); ?></p>
        <p>Phone: <?php echo esc_html(get_option('aipd_company_phone', '0123456789')); ?></p>
        <p>Email: <?php echo esc_html(get_option('aipd_company_email', 'email@example.com')); ?></p>
    </div>
    <h1>Package #<?php echo $order->get_id(); ?></h1>
</header>

<div class="customer-info">
    <p><strong>Customer:</strong> <?php echo esc_html($order->get_formatted_billing_full_name()); ?></p>
    <p><strong>Shipping Address:</strong> <?php echo esc_html($order->get_formatted_shipping_address()); ?></p>
    <p><strong>Date:</strong> <?php echo esc_html(wc_format_datetime($order->get_date_created())); ?></p>
</div>

<table>
    <thead>
        <tr>
            <th>Product</th>
            <th>SKU</th>
            <th>Qty</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($order->get_items() as $item):
            $product = $item->get_product();
            $sku = $product ? $product->get_sku() : '';
        ?>
        <tr>
            <td><?php echo esc_html($item->get_name()); ?></td>
            <td><?php echo esc_html($sku); ?></td>
            <td><?php echo esc_html($item->get_quantity()); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php if($order->get_customer_note()): ?>
<div class="notes">
    <strong>Special Instructions / Customer Notes:</strong>
    <p><?php echo esc_html($order->get_customer_note()); ?></p>
</div>
<?php endif; ?>

<div class="footer">
    <?php echo esc_html(get_option('aipd_footer_text','Thank you for your order!')); ?><br>
    Generated by <?php bloginfo('name'); ?>.
</div>

</body>
</html>
